# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orchlane < Formula
  desc "Local-first AI development proxy and context engine"
  homepage "https://github.com/Kobie-Bendalak/OrchLane"
  version "5.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kobie-Bendalak/orchlane-dist/releases/download/v5.0.0/orchlane_5.0.0_darwin_x86_64.tar.gz"
      sha256 "47e78a6f2f9bc5dae4bcd709e277a7aa55e07bc8f94d27d2af90ed39bbc07445"

      define_method(:install) do
        bin.install "orchlane"
        generate_completions_from_executable(bin/"orchlane", "completion")

        # Install scripts for all ENVs by default
        libexec.install "scripts/ml_inference_server.py"
        libexec.install Dir["scripts/*watchdog*"]
        libexec.install "scripts/start-mcp.sh"
        libexec.install Dir["scripts/install-*.sh"]

        # Extract prebuilt venv with all orchlane_context dependencies already installed
        system "tar", "-xzf", "venv.tar.gz", "-C", libexec
        system "mv", File.join(libexec, "orchlane-build-venv"), File.join(libexec, "venv")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kobie-Bendalak/orchlane-dist/releases/download/v5.0.0/orchlane_5.0.0_darwin_arm64.tar.gz"
      sha256 "6b8809d2edd7e13cc07cb4e099b7b9f13448402210dc5db0b9039a8e05c863e5"

      define_method(:install) do
        bin.install "orchlane"
        generate_completions_from_executable(bin/"orchlane", "completion")

        # Install scripts for all ENVs by default
        libexec.install "scripts/ml_inference_server.py"
        libexec.install Dir["scripts/*watchdog*"]
        libexec.install "scripts/start-mcp.sh"
        libexec.install Dir["scripts/install-*.sh"]

        # Extract prebuilt venv with all orchlane_context dependencies already installed
        system "tar", "-xzf", "venv.tar.gz", "-C", libexec
        system "mv", File.join(libexec, "orchlane-build-venv"), File.join(libexec, "venv")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kobie-Bendalak/orchlane-dist/releases/download/v5.0.0/orchlane_5.0.0_linux_x86_64.tar.gz"
      sha256 "fa8f3cb0693d03fa212b8af86da965b2b6c88bcabd82581a81aaa571144178ce"
      define_method(:install) do
        bin.install "orchlane"
        generate_completions_from_executable(bin/"orchlane", "completion")

        # Install scripts for all ENVs by default
        libexec.install "scripts/ml_inference_server.py"
        libexec.install Dir["scripts/*watchdog*"]
        libexec.install "scripts/start-mcp.sh"
        libexec.install Dir["scripts/install-*.sh"]

        # Extract prebuilt venv with all orchlane_context dependencies already installed
        system "tar", "-xzf", "venv.tar.gz", "-C", libexec
        system "mv", File.join(libexec, "orchlane-build-venv"), File.join(libexec, "venv")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kobie-Bendalak/orchlane-dist/releases/download/v5.0.0/orchlane_5.0.0_linux_arm64.tar.gz"
      sha256 "9cf5f82fa4aa9c7aa07990e11499d1013413a3272001c912fb7dbd44828bc286"
      define_method(:install) do
        bin.install "orchlane"
        generate_completions_from_executable(bin/"orchlane", "completion")

        # Install scripts for all ENVs by default
        libexec.install "scripts/ml_inference_server.py"
        libexec.install Dir["scripts/*watchdog*"]
        libexec.install "scripts/start-mcp.sh"
        libexec.install Dir["scripts/install-*.sh"]

        # Extract prebuilt venv with all orchlane_context dependencies already installed
        system "tar", "-xzf", "venv.tar.gz", "-C", libexec
        system "mv", File.join(libexec, "orchlane-build-venv"), File.join(libexec, "venv")
      end
    end
  end

  def caveats
    <<~EOS
      OrchLane needs Docker Desktop (or another docker-compose-capable daemon)
      running to start its services.

      First run:
        orchlane init       # detects Keychain OAuth, writes ~/.orchlane/env, pulls images
        orchlane start      # bring the stack up
        orchlane doctor     # verify everything is wired

      Auto-start at login (optional):
        orchlane service install

      Point your IDE at the proxy:
        export ANTHROPIC_BASE_URL=http://localhost:7878
    EOS
  end

  test do
    system bin/"orchlane", "--help"
  end
end
