# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orchlane < Formula
  desc "Local-first AI development proxy and context engine"
  homepage "https://github.com/Kobie-Bendalak/OrchLane"
  version "5.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kobie-Bendalak/orchlane-dist/releases/download/v5.1.0/orchlane_5.1.0_darwin_x86_64.tar.gz"
      sha256 "24bf7c8d8402e6cc5f76c94417fb1e2b765f1b0627d4641a4ddc7aca6951ec62"

      define_method(:install) do
        bin.install "orchlane"
        generate_completions_from_executable(bin/"orchlane", "completion")

        # Install scripts for all ENVs by default
        libexec.install "scripts/ml_inference_server.py"
        libexec.install Dir["scripts/*watchdog*"]
        libexec.install "scripts/start-mcp.sh"
        libexec.install Dir["scripts/install-*.sh"]

        # Extract prebuilt venv with all orchlane_context dependencies already installed
        system "tar", "-xzf", "venv.tar.gz", "-C", libexec
        system "mv", File.join(libexec, "orchlane-build-venv"), File.join(libexec, "venv")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kobie-Bendalak/orchlane-dist/releases/download/v5.1.0/orchlane_5.1.0_darwin_arm64.tar.gz"
      sha256 "9ed9b7b8aaf2cb0617f809eda685596e8fdc491844e5874dc3396e6c72fb74ad"

      define_method(:install) do
        bin.install "orchlane"
        generate_completions_from_executable(bin/"orchlane", "completion")

        # Install scripts for all ENVs by default
        libexec.install "scripts/ml_inference_server.py"
        libexec.install Dir["scripts/*watchdog*"]
        libexec.install "scripts/start-mcp.sh"
        libexec.install Dir["scripts/install-*.sh"]

        # Extract prebuilt venv with all orchlane_context dependencies already installed
        system "tar", "-xzf", "venv.tar.gz", "-C", libexec
        system "mv", File.join(libexec, "orchlane-build-venv"), File.join(libexec, "venv")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kobie-Bendalak/orchlane-dist/releases/download/v5.1.0/orchlane_5.1.0_linux_x86_64.tar.gz"
      sha256 "112eed261b08b6c502d9e1f108617ac29a96a1abe820ca69322488ba4a33a790"
      define_method(:install) do
        bin.install "orchlane"
        generate_completions_from_executable(bin/"orchlane", "completion")

        # Install scripts for all ENVs by default
        libexec.install "scripts/ml_inference_server.py"
        libexec.install Dir["scripts/*watchdog*"]
        libexec.install "scripts/start-mcp.sh"
        libexec.install Dir["scripts/install-*.sh"]

        # Extract prebuilt venv with all orchlane_context dependencies already installed
        system "tar", "-xzf", "venv.tar.gz", "-C", libexec
        system "mv", File.join(libexec, "orchlane-build-venv"), File.join(libexec, "venv")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kobie-Bendalak/orchlane-dist/releases/download/v5.1.0/orchlane_5.1.0_linux_arm64.tar.gz"
      sha256 "b2c75e18df83abd830cf6c75a7959f7c6c7bf0d48f8f25040af54c12b2763c26"
      define_method(:install) do
        bin.install "orchlane"
        generate_completions_from_executable(bin/"orchlane", "completion")

        # Install scripts for all ENVs by default
        libexec.install "scripts/ml_inference_server.py"
        libexec.install Dir["scripts/*watchdog*"]
        libexec.install "scripts/start-mcp.sh"
        libexec.install Dir["scripts/install-*.sh"]

        # Extract prebuilt venv with all orchlane_context dependencies already installed
        system "tar", "-xzf", "venv.tar.gz", "-C", libexec
        system "mv", File.join(libexec, "orchlane-build-venv"), File.join(libexec, "venv")
      end
    end
  end

  def caveats
    <<~EOS
      OrchLane needs Docker Desktop (or another docker-compose-capable daemon)
      running to start its services.

      First run:
        orchlane init       # detects Keychain OAuth, writes ~/.orchlane/env, pulls images
        orchlane start      # bring the stack up
        orchlane doctor     # verify everything is wired

      Auto-start at login (optional):
        orchlane service install

      Point your IDE at the proxy:
        export ANTHROPIC_BASE_URL=http://localhost:7878
    EOS
  end

  test do
    system bin/"orchlane", "--help"
  end
end
