# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orchlane < Formula
  desc "Local-first AI development proxy and context engine"
  homepage "https://github.com/Kobie-Bendalak/OrchLane"
  version "4.0.21"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kobie-Bendalak/orchlane-dist/releases/download/v4.0.21/orchlane_4.0.21_darwin_x86_64.tar.gz"
      sha256 "6ce270de7a41cbf6c0a87b25c7b4b490277fdcc37d55330ded259219b908d290"

      define_method(:install) do
        bin.install "orchlane"
        generate_completions_from_executable(bin/"orchlane", "completion")

        # Install scripts for all ENVs by default
        libexec.install "scripts/ml_inference_server.py"
        libexec.install Dir["scripts/*watchdog*"]
        libexec.install "scripts/start-mcp.sh"

        # Install the MCP server Python package into a managed venv so
        # start-mcp.sh works without a dev-repo context/ directory present.
        system "python3", "-m", "venv", libexec/"venv"
        system libexec/"venv/bin/pip", "install",
               Dir["wheels/orchlane_context-*.whl"].first
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kobie-Bendalak/orchlane-dist/releases/download/v4.0.21/orchlane_4.0.21_darwin_arm64.tar.gz"
      sha256 "1e818c3af8c3950e726828549da45964896af610d0b467dbb9a265a22e4fe431"

      define_method(:install) do
        bin.install "orchlane"
        generate_completions_from_executable(bin/"orchlane", "completion")

        # Install scripts for all ENVs by default
        libexec.install "scripts/ml_inference_server.py"
        libexec.install Dir["scripts/*watchdog*"]
        libexec.install "scripts/start-mcp.sh"

        # Install the MCP server Python package into a managed venv so
        # start-mcp.sh works without a dev-repo context/ directory present.
        system "python3", "-m", "venv", libexec/"venv"
        system libexec/"venv/bin/pip", "install",
               Dir["wheels/orchlane_context-*.whl"].first
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kobie-Bendalak/orchlane-dist/releases/download/v4.0.21/orchlane_4.0.21_linux_x86_64.tar.gz"
      sha256 "751f3fd9ff1b84a99193ce2cff26306fadac9c7f5f781842b234ae87642aeb4a"
      define_method(:install) do
        bin.install "orchlane"
        generate_completions_from_executable(bin/"orchlane", "completion")

        # Install scripts for all ENVs by default
        libexec.install "scripts/ml_inference_server.py"
        libexec.install Dir["scripts/*watchdog*"]
        libexec.install "scripts/start-mcp.sh"

        # Install the MCP server Python package into a managed venv so
        # start-mcp.sh works without a dev-repo context/ directory present.
        system "python3", "-m", "venv", libexec/"venv"
        system libexec/"venv/bin/pip", "install",
               Dir["wheels/orchlane_context-*.whl"].first
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kobie-Bendalak/orchlane-dist/releases/download/v4.0.21/orchlane_4.0.21_linux_arm64.tar.gz"
      sha256 "6dffa1952399f87edf815d6b5e969448fea0ad0042b24f7863dc9aa0e1bce6b2"
      define_method(:install) do
        bin.install "orchlane"
        generate_completions_from_executable(bin/"orchlane", "completion")

        # Install scripts for all ENVs by default
        libexec.install "scripts/ml_inference_server.py"
        libexec.install Dir["scripts/*watchdog*"]
        libexec.install "scripts/start-mcp.sh"

        # Install the MCP server Python package into a managed venv so
        # start-mcp.sh works without a dev-repo context/ directory present.
        system "python3", "-m", "venv", libexec/"venv"
        system libexec/"venv/bin/pip", "install",
               Dir["wheels/orchlane_context-*.whl"].first
      end
    end
  end

  def caveats
    <<~EOS
      OrchLane needs Docker Desktop (or another docker-compose-capable daemon)
      running to start its services.

      First run:
        orchlane init       # detects Keychain OAuth, writes ~/.orchlane/env, pulls images
        orchlane start      # bring the stack up
        orchlane doctor     # verify everything is wired

      Auto-start at login (optional):
        orchlane service install

      Point your IDE at the proxy:
        export ANTHROPIC_BASE_URL=http://localhost:7878
    EOS
  end

  test do
    system bin/"orchlane", "--help"
  end
end
